components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.1.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 8647693dbf6a0d47b1ef0f3dea3f6b172cc07093
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 63640afc4df6e27185456a27f238d1f488b63b28
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 204eddca76b5790ea901e8b96b2a9170502373ee
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 57e0a77511edfc4ca0e42b939075d1ab23c48a09
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v0.91.10
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 3232e5d67b5c3dd2323f13bede3ab1558b5aa4b9-1401
converter: M-1412
version: '1'
